### ISSUE TITLE
Na installatie error in Backend

### ISSUE THREAD

**Issue by Tristan-N** [experius/Magento-2-Module-Experius-Email-Catcher#11]
Na het navigeren naar System -> Tools -> Email catcher krijg ik de volgende foutmelding:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tablename_magento.experius_emailcatcher' doesn't exist, query was: SELECT COUNT(*) FROM `experius_emailcatcher` AS `main_table``

De betreffende tabel is niet aangemaakt in de database. Alle stappen voor installatie module doorlopen inclusief setup:upgrade, cache:flush en verwijderen van pub/static/* var/di etc etc.

edit: tabelnaam verwijderd uit foutmelding uit veiligheidsoverwegingen.

**Comment by dheesbeen** [comment]
Hoi Tristan, 

Ik heb zojuist de module op twee module op twee omgevingen geinstalleerd maar ik kan jou melding niet reproduceren. 

Wellicht even het record helemaal verwijderen uit je setup_module table en dan nog een keer bin/magento setup:upgrade runnen
