### ISSUE TITLE
Please make it compatible with 2.2

### ISSUE THREAD

**Issue by mikehenze** [experius/Magento-2-Module-Experius-Email-Catcher#13]
PHP Fatal error:  Class Experius\EmailCatcher\Mail\Transport contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Magento\Framework\Mail\TransportInterface::getMessage) in /data/web/magento2/vendor/experius/emailcatcher/Mail/Transport.php on line 16

**Comment by dheesbeen** [comment]
Thanks for reporting. We will fix this soon

**Comment by dheesbeen** [comment]
solved in version 1.1.0
