### ISSUE TITLE
Subject special charts

### ISSUE THREAD

**Issue by dheesbeen** [experius/Magento-2-Module-Experius-Email-Catcher#16]
Issue with special chars 

Example: Réinitialiser votre mot de masse

**Comment by mikehenze** [comment]
Another example:

[#SZL-117-45459] AW: Bitte Überprüfen Sie Ihre gekauften Produkte

becomes

=?utf-8?Q?AW:=20Bitte=20=C3=9Cberpr=C3=BCfen=20Sie=20Ihre=20?= =?utf-8?Q?gekauften=20Produkte?=

**Comment by dheesbeen** [comment]
Great thanks

**Comment by dheesbeen** [comment]
solved 1.1.0
