### ISSUE TITLE
Not compatible with 2.3

### ISSUE THREAD

**Issue by mikehenze** [experius/Magento-2-Module-Experius-Email-Catcher#23]
Fatal error: Uncaught Error: Call to undefined method Zend\Mime\Message::getRawContent() in /data/web/magento2/vendor/experius/emailcatcher/Model/Emailcatcher.php:38 Stack trace: #0 /data/web/magento2/vendor/experius/emailcatcher/Plugin/Magento/Framework/Mail/TransportInterface.php(34): Experius\EmailCatcher\Model\Emailcatcher->saveMessage(Object(Magento\Framework\Mail\Message)) #1 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Experius\EmailCatcher\Plugin\Magento\Framework\Mail\TransportInterface->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #2 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}() #3 /data/web/magento2/generated/code/Magento/Email/Model/Transport/Interceptor.php(26): Magento\Email\Model\Transport\Interceptor->___callPlugins('sendMessage', Array, Array) #4 /data/web/magento2/vendor/magento/module-sales/Model/Order/Email/Send in /data/web/magento2/vendor/experius/emailcatcher/Model/Emailcatcher.php on line 38

**Comment by dheesbeen** [comment]
@mikehenze are you running on version 2.2.1?

**Comment by mikehenze** [comment]
Seems I am running an old version (1.3.10) because it was hardcoded in my composer.json.
Updating will most likely make it compatible with M2.3

Thanks for point out! :)

**Comment by mikehenze** [comment]
Yeah fully working now.
