### ISSUE TITLE
Sorting error by user from

### ISSUE THREAD

**Issue by thokiller** [experius/Magento-2-Module-Experius-Email-Catcher#27]
When you want to order in the column from a error appears: 
"Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from ASC LIMIT 100' at line 1 SQL was: SELECT main_table.* FROM experius_emailcatcher AS main_table ORDER BY from ASC LIMIT 100"
error is because the wordt from is reserved. it can be fixed by escaping the `from`.
@dheesbeen

**Comment by dheesbeen** [comment]
@thokiller This is fixed
