### ISSUE TITLE
Latest release is broke for new installations

### ISSUE THREAD

**Issue by igor-imaginemage** [experius/Magento-2-Module-Experius-Email-Catcher#32]
Hi,

if you try to install the module for the first time in a Magento store it will also execute the UpgradeSchema script and as there is no "to" column in the database you will receive an error.

https://prnt.sc/p4v2pn

**Comment by thampe** [comment]
Hi,

there is a pending PR (#33) for this.

**Comment by dheesbeen** [comment]
@igor-imaginemage This is fixed
