### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Experius\EmailCatcher\Model\imap_utf8()

### ISSUE THREAD

**Issue by kaushalsutharoc** [experius/Magento-2-Module-Experius-Email-Catcher#47]
Getting following error

Magento 2.3.4
PHP 7.2
`
Fatal error: Uncaught Error: Call to undefined function Experius\EmailCatcher\Model\imap_utf8() in /app/vendor/experius/module-emailcatcher/Model/Emailcatcher.php:97 Stack trace: #0 /app/vendor/experius/module-emailcatcher/Plugin/Magento/Framework/Mail/TransportInterface.php(89): Experius\EmailCatcher\Model\Emailcatcher->saveMessage(Object(Magento\Framework\Mail\EmailMessage\Interceptor)) #1 /app/vendor/experius/module-emailcatcher/Plugin/Magento/Framework/Mail/TransportInterface.php(63): Experius\EmailCatcher\Plugin\Magento\Framework\Mail\TransportInterface->saveMessage(Object(Experius\EmailCatcher\Rewrite\Magento\Email\Model\Transport\Interceptor)) #2 /app/vendor/magento/framework/Interception/Interceptor.php(135): Experius\EmailCatcher\Plugin\Magento\Framework\Mail\TransportInterface->aroundSendMessage(Object(Experius\EmailCatcher\Rewrite\Magento\Email\Model\Transport\Interceptor), Object(Closure)) #3 /app/vendor/magento/framework/Interception/Interceptor.php(153): Experius\EmailCatcher\Rewrite\Magento\Email\Model\Tran in /app/vendor/experius/module-emailcatcher/Model/Emailcatcher.php on line 97`

**Comment by dheesbeen** [comment]
@kaushalsutharoc The IMAP extension is not activated in your PHP installation

**Comment by Tomasz-Silpion** [comment]
IMAP extension is not part of Magento 2 requirements so in my opinion this should be protected with function_exists call.
