### ISSUE TITLE
Apply whitelist function in M 2.3.4 disables all e-mail communication

### ISSUE THREAD

**Issue by pascalexperius** [experius/Magento-2-Module-Experius-Email-Catcher#50]
**Action:**
- Apply whitelist = Yes
- Select e-mails to add to this whitelist

**Result:**
None of the e-mails is send

Tested on: Magento ver. 2.3.4
Module version 3.1.3

**Comment by borisvankatwijk** [comment]
Hi @pascalexperius ,

Is this still relevant, or can the issue be removed/closed?

**Comment by pascalexperius** [comment]
@borisvankatwijk in my opinion this issue could be closed since someone shouldn't use Magento 2.3.4 anymore :-)
