### ISSUE TITLE
Cron issue on Magento Commerce 2.4.3-p1

### ISSUE THREAD

**Issue by jlenzstaysafe** [experius/Magento-2-Module-Experius-Email-Catcher#62]
report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:368, Error(code: 0): Call to undefined method Magento\\Framework\\Logger\\LoggerProxy::addInfo() at /vendor/experius/module-emailcatcher/Cron/Clean.php:74)"} []

**Comment by AboElnoor** [comment]
In my system, I get the report daily the cleanup cron has an error during running.

**Comment by mageprashant** [comment]
@manuelcanepa Issue is fixed here: https://github.com/experius/Magento-2-Module-Experius-Email-Catcher/pull/64

**Comment by borisvankatwijk** [comment]
Hi @jlenzstaysafe ,

This should be resolved now.
