### ISSUE TITLE
ERROR: Run Cleanup

### ISSUE THREAD

**Issue by bruce-gemberling** [experius/Magento-2-Module-Experius-Email-Catcher#63]
When I attempted to RUN CLEANUP I received this error:

Error: Call to undefined method Magento\Framework\Logger\LoggerProxy::addInfo() in vendor/experius/module-emailcatcher/Cron/Clean.php:74

**Comment by borisvankatwijk** [comment]
Hi @mageprashant,

I forgot to close the issue, or mention it. I think it's resolved now. :-)
