### ISSUE TITLE
ERROR: Run Cleanup

### ISSUE THREAD

**Issue by vivekmaharjan** [experius/Magento-2-Module-Experius-Email-Catcher#67]
When I attempted to RUN CLEANUP I received this error:

(Exception): Deprecated Functionality: Creation of dynamic property Experius\EmailCatcher\Cron\Clean::$connection is deprecated in /var/www/magento/vendor/experius/emailcatcher/Cron/Clean.php on line 49

**Comment by borisvankatwijk** [comment]
Hi @vivekmaharjan ,

We resolved this issue in release 3.5.3.

Thank you for noticing and creating the issue.
